#
# Module manifest for module 'PublishModulesAndMofsToPullServer'
#
# Generated by: Narine Mossikyan
#
# Generated on: 3/10/2016
#
@{
# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = 'e4685473-cdc7-4396-bfbf-eab80e6f029d'

# Author of this module
Author = 'Narine Mossikyan'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = '(c) 2014 Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PublishModulesAndMofsToPullServer module is a part of the Windows PowerShell Desired State Configuration (DSC) Resource Kit, which is a collection of DSC Resources produced by the PowerShell Team. This module contains helpers to package configuration documents and DSC modules from local path or Powershell module path and publish them on the DSC pull server endpoint.'

# Minimum version of the Windows PowerShell engine required by this module
#PowerShellVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
#CLRVersion = ''

# Functions to export from this module
FunctionsToExport = 'Publish-DSCModulesAndMofs'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('DSC pullserver module packaging', 'DSC', 'PullServer', 'DSCPullServer')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/PowerShell/xPSDesiredStateConfiguration/DSCPullServerSetup'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'https://github.com/PowerShell/xPSDesiredStateConfiguration/DSCPullServerSetup/README.md'


    } # End of PSData hashtable

} # End of PrivateData hashtable
}


