[ClassVersion("1.0.0"),FriendlyName("xMsiPackage")] 
class MSFT_xMsiPackage : OMI_BaseResource
{
  [Key, Description("")] String ProductId;
  [Required, Description("")] String Path;
  [Write, Description(""), ValueMap{"Present", "Absent"}, Values{"Present", "Absent"}] String Ensure;
  [Write, Description("")] String Arguments;
  [Write, Description(""), EmbeddedInstance("MSFT_Credential")] String Credential;
  [Write, Description("")] String LogPath;
  [Write, Description("")] String FileHash;
  [Write, Description(""), ValueMap{"SHA1","SHA256","SHA384","SHA512","MD5","RIPEMD160"}, Values{"SHA1","SHA256","SHA384","SHA512","MD5","RIPEMD160"}] String HashAlgorithm;
  [Write, Description("")] String SignerSubject;
  [Write, Description("")] String SignerThumbprint;
  [Write, Description("")] String ServerCertificateValidationCallback;
  [Write, Description(""), EmbeddedInstance("MSFT_Credential")] String RunAsCredential;
  [Read, Description("")] String Name;
  [Read, Description("")] String InstallSource;
  [Read, Description("")] String InstalledOn;
  [Read, Description("")] UInt32 Size;
  [Read, Description("")] String Version;
  [Read, Description("")] String PackageDescription;
  [Read, Description("")] String Publisher;
};
