[ClassVersion("1.0.0"), FriendlyName("xEnvironment")] 
class MSFT_xEnvironmentResource : OMI_BaseResource
{
  [Key] String Name;
  [Write] String Value;
  [Write, ValueMap{"Present", "Absent"}, Values{"Present", "Absent"}] String Ensure;
  [Write] Boolean Path;
  [Write, ValueMap{"Process", "Machine"}, Values{"Process", "Machine"}] String Target[];
};
