[ClassVersion("1.0.0"), FriendlyName("xWindowsProcess")] 
class MSFT_xProcessResource : OMI_BaseResource
{
  [Key] String Path;
  [Key] String Arguments;
  [Write, EmbeddedInstance("MSFT_Credential")] String Credential;
  [Write, ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] String Ensure;
  [Write] String StandardOutputPath;
  [Write] String StandardErrorPath;
  [Write] String StandardInputPath;
  [Write] String WorkingDirectory;
  [Read] Uint64 PagedMemorySize;
  [Read] Uint64 NonPagedMemorySize;
  [Read] Uint64 VirtualMemorySize;
  [Read] Sint32 HandleCount;
  [Read] Sint32 ProcessId;
  [Read] Sint32 ProcessCount;
};
