[ClassVersion("1.0.0"), FriendlyName("xWindowsProcess")] 
class MSFT_xProcessResource : OMI_BaseResource
{
  [key] string Path;
  [key] string Arguments;
  [write,EmbeddedInstance("MSFT_Credential")] string Credential;
  [write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
  [write] string StandardOutputPath;
  [write] string StandardErrorPath;
  [write] string StandardInputPath;
  [write] string WorkingDirectory;
  [read] uint64 PagedMemorySize;
  [read] uint64 NonPagedMemorySize;
  [read] uint64 VirtualMemorySize;
  [read] sint32 HandleCount;
  [read] sint32 ProcessId;
};


