[ClassVersion("1.0.0.0"), FriendlyName("xPSEndpoint")]
class DSC_xPSSessionConfiguration : OMI_BaseResource
{
    [Key, Description("Name of the PS Remoting Endpoint")] String Name;
    [Write, Description("Whether to create the endpoint or delete it"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Path for the startup script")] String StartupScript;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("Credential for Running under different user context")] String RunAsCredential;
    [Write, Description("SDDL for allowed users to connect to this endpoint")] String SecurityDescriptorSDDL;
    [Write, Description("Whether the endpoint is remotely accessible or has local access only or no access"), ValueMap{"Local","Remote", "Disabled"}, Values{"Local","Remote","Disabled"}] String AccessMode;
};

