[ClassVersion("1.0.0"), FriendlyName("xDSCWebService")] 
class MSFT_xDSCWebService : OMI_BaseResource
{
  [Key] string EndpointName;
  [write, Description("Can take the value AllowUnencryptedTraffic for setting up a non SSL based endpoint")]
  string CertificateThumbPrint;
  [write] string CertificateSubject;
  [write] string CertificateTemplateName;
  [write] uint32 Port;
  [write] string PhysicalPath;
  [write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
  [write,ValueMap{"Started","Stopped"},Values{"Started", "Stopped"}] string State;
  [write] string DatabasePath;
  [write] string ModulePath;
  [write] string ConfigurationPath;
  [read] string DSCServerUrl;  
  [write] string RegistrationKeyPath;
  [write] boolean AcceptSelfSignedCertificates;
  [write] boolean SqlProvider;
  [write] string SqlConnectionString;
  [required, Description("This property will ensure that the Pull Server is created with the most secure practices")] boolean UseSecurityBestPractices;
  [write,ValueMap{"SecureTLSProtocols"},Values{"SecureTLSProtocols"}] string DisableSecurityBestPractices [];
  [write, Description("When this property is set to true, Pull Server will run on a 32 bit process on a 64 bit machine")] boolean Enable32BitAppOnWin64;
};
